# Generated by Django 3.2 on 2020-11-25 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeWork',
            fields=[
                ('anime_id', models.IntegerField(primary_key=True, serialize=False)),
                ('anime_name', models.CharField(max_length=50)),
                ('anime_description', models.CharField(max_length=500)),
                ('anime_avatar_url', models.CharField(default=None, max_length=300)),
                ('anime_cover_image_url', models.CharField(default=None, max_length=300)),
                ('anime_rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('anime_airing_start_date', models.DateField(auto_now_add=True)),
                ('anime_airing_end_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=25)),
                ('user_cookie', models.CharField(max_length=300)),
                ('user_email', models.CharField(max_length=50)),
                ('user_avatar_url', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
                ('tag_anime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animes.animework')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.IntegerField(primary_key=True, serialize=False)),
                ('review_content', models.CharField(max_length=10000)),
                ('review_date_created', models.DateTimeField(auto_now_add=True)),
                ('review_date_modified', models.DateTimeField(auto_now=True)),
                ('review_upvotes', models.IntegerField(default=0)),
                ('review_anime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animes.animework')),
                ('reviewer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animes.user')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_anime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animes.animework')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animes.question')),
            ],
        ),
    ]
