# Generated by Django 3.2 on 2020-11-26 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animework',
            name='anime_airing_end_date',
        ),
        migrations.RemoveField(
            model_name='animework',
            name='anime_airing_start_date',
        ),
    ]
