# Generated by Django 3.2 on 2020-11-22 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeWork',
            fields=[
                ('anime_id', models.IntegerField(primary_key=True, serialize=False)),
                ('anime_name', models.CharField(max_length=50)),
                ('anime_description', models.CharField(max_length=500)),
                ('anime_avatar_url', models.CharField(max_length=300)),
                ('anime_cover_image_url', models.CharField(max_length=300)),
                ('anime_rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('anime_aring_start_date', models.DateTimeField()),
                ('anime_aring_end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=25)),
                ('user_cookie', models.CharField(max_length=300)),
                ('user_email', models.CharField(max_length=50)),
                ('user_avatar_url', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
                ('tag_anime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.animework')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.IntegerField(primary_key=True, serialize=False)),
                ('review_content', models.CharField(max_length=10000)),
                ('review_date_created', models.DateTimeField(auto_now_add=True)),
                ('review_date_modified', models.DateTimeField(auto_now=True)),
                ('review_upvotes', models.IntegerField(default=0)),
                ('review_anime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.animework')),
                ('reviewer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.user')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_anime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.animework')),
            ],
        ),
    ]
